name: Deploy Frontend

on:
  push:
    branches:
      - main
    paths:
      - 'chat-front/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 45.138.159.166
          username: deploy
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

            cd /var/www/chat-front
            git pull origin main
            npm install
            npm run build
            pm2 restart chat-front || pm2 start npm --name "chat-front" -- start
